name: deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
    steps:
      - run: mkdir -p ~/.ssh/
      - run: echo "$SSH_KEY" > ~/.ssh/deploy.key
      - run: chmod 600 ~/.ssh/deploy.key
      - run: ssh -o StrictHostKeychecking=no -i ~/.ssh/deploy.key $SSH_USER@$SSH_HOST
